name: Continuous Integration
on: push

jobs:
  unit-test:
    name: Unit Testing
    runs-on: ubuntu-latest
    steps:
    - name: Setup
      shell: bash
      run: |
        docker-compose build
        docker-compose run web bundle exec rails db:create
    - name: Rspec
      shell: bash
      run: |
        docker-compose run web bundle exec rspec