name: Continuous Integration
on: push

jobs:
  unit-test:
    name: Unit Testing
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup
      shell: bash
      run: |
        docker-compose build
        docker-compose run web bundle exec rails db:create
    - name: Rspec
      shell: bash
      run: |
        docker-compose run web bundle exec rspec
  deploy:
    name: Deploy to heroku
    needs: unit-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.8.8
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          usedocker: true